name: Go

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.15'
          - '1.14'
          - '1.13'

    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          mkdir -pv "$(go env GOPATH)/src/github.com/plexdrive"
          ln -nfsv "$PWD" "$(go env GOPATH)/src/github.com/plexdrive/plexdrive"
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
